require	'sinatra'
require 'json'
require 'date'

# { :number => , :location => "", :published => Date.new(2012, 4, 26), :name => "", :url => "", :description => "", :photo => "", :video => "", :imdb => "" },

episodes = [
	{ :number => 90, :location => "http://badmoviepodcast.com/2012/08/episode-90-ninja-3-domination/", :published => Date.new(2012, 8, 17), :name => "Ninja 3 – Domination", :url => "http://www.podtrac.com/pts/redirect.mp3/www.badmoviepodcast.com/mp3/e090_ninja3domaination.mp3", :description => "An evil ninja transfers his soul into a sexy dancer, then goes on a killing spree. Thoroughly 80s in every way.", :photo => "http://badmoviepodcast.com/images/e090_ninja3domaination.jpg", :video => "http://www.youtube.com/watch?v=Lka47oegL54", :imdb => "http://www.imdb.com/title/tt0087805/" },
	{ :number => 89, :location => "http://badmoviepodcast.com/2012/07/episode-89-hard-ticket-to-hawaii/", :published => Date.new(2012, 7, 16), :name => "Hard Ticket to Hawaii", :url => "http://www.podtrac.com/pts/redirect.mp3/www.badmoviepodcast.com/mp3/e089_hardtickethawaii.mp3", :description => "Two busty lovelies and a monster snake fight bad guys in hawaii. Clothing optional. Hot tubs and rocket launchers mandatory.", :photo => "http://badmoviepodcast.com/images/e089_hardtickethawaii.jpg", :video => "http://www.youtube.com/watch?v=Vzv_6dFtKDE", :imdb => "http://www.imdb.com/title/tt0093146/" },
	{ :number => 88, :location => "http://badmoviepodcast.com/2012/07/episode-88-roller-blade/", :published => Date.new(2012, 7, 05), :name => "Roller Blade", :url => "http://www.podtrac.com/pts/redirect.mp3/www.badmoviepodcast.com/mp3/e088_RollerBlade.mp3", :description => "Post-apocalyptic roller skating nuns with daggers of love vs. a luchador and his puppet. WORST MOVIE EVER SEEN AWARD (Probably because we haven't seen his other 5 rollerblade movies). It's true, we haven't seen a shittier movie in all our lives.", :photo => "http://badmoviepodcast.com/images/e088_RollerBlade.jpg", :video => "http://www.youtube.com/watch?v=EAz_RF5Lrjw", :imdb => "http://www.imdb.com/title/tt0089930/" },
	{ :number => 87, :location => "http://badmoviepodcast.com/2012/06/episode-87-galaxis/", :published => Date.new(2012, 6, 29), :name => "Galaxis", :url => "http://www.podtrac.com/pts/redirect.mp3/www.badmoviepodcast.com/mp3/e087_galaxis.mp3", :description => "Bridgette Nielsen as Space Madonna from her leather Marilyn Monroe period comes to earth seeking the crystal. Richard Moll would like it too. You won't even believe this bullshit is as recent as 1995, it's so 1986.", :photo => "http://badmoviepodcast.com/images/e087_galaxis.jpg", :video => "http://www.youtube.com/watch?v=Tbd6bN7pKsg", :imdb => "http://www.imdb.com/title/tt0113140/" },
	{ :number => 86, :location => "http://badmoviepodcast.com/2012/06/episode-86-dragon-force/", :published => Date.new(2012, 6, 20), :name => "Dragon Force", :url => "http://www.podtrac.com/pts/redirect.mp3/www.badmoviepodcast.com/mp3/e086_dragonforce.mp3", :description => "The best damn ninja movie we’ve ever seen. Head-explodingly ridiculous. We love you XOXOXO", :photo => "http://badmoviepodcast.com/images/e086_dragonforce.jpg", :video => "http://www.youtube.com/watch?v=oF0Flg04OB0", :imdb => "http://www.imdb.com/title/tt0082936/" },
	{ :number => 85, :location => "http://badmoviepodcast.com/2012/06/episode-85-rising-storm/", :published => Date.new(2012, 6, 15), :name => "Rising Storm", :url => "http://www.podtrac.com/pts/redirect.mp3/www.badmoviepodcast.com/mp3/e085_RisingStorm.mp3", :description => "Praise the lord. I lull Josh into a false sense of security, and the BLOW HIS MIND with religio-politics. This is a movie with a MESSAGE. Praise the lord.", :photo => "http://badmoviepodcast.com/images/e085_risingstorm.jpg", :video => "http://www.youtube.com/watch?v=gWvZ5FgqYJ4", :imdb => "http://www.imdb.com/title/tt0100464/" },
	{ :number => 84, :location => "http://badmoviepodcast.com/2012/06/episode-84-sharkman/", :published => Date.new(2012, 6, 07), :name => "SharkMan", :url => "http://www.podtrac.com/pts/redirect.mp3/www.badmoviepodcast.com/mp3/e084_SharkMan.mp3", :description => "Who are you?! I'm SHARKMAN! CORNFLAKES. Like the panda bear, SharkMan won't have sex with the ladies. Hunter Tylo's DSLs try to save the day. +1 for heroic IT guy.", :photo => "http://badmoviepodcast.com/images/e084_SharkMan.jpg", :video => "http://www.youtube.com/watch?v=u0ShkmRR6y8", :imdb => "http://www.imdb.com/title/tt0459392/" },
	{ :number => 83, :location => "http://badmoviepodcast.com/2012/05/episode-83-the-wraith/", :published => Date.new(2012, 5, 22), :name => "The Wraith", :url => "http://badmoviepodcast.com/mp3/e083_thewraith.mp3", :description => "@DrQuest decided to torture us with the first AND LAST viewer requested movie. Charlie Sheen was hardly in it. We hardly talked about it. Yet the pain was still unbearable. I\'ll be in therapy for a while.", :photo => "http://badmoviepodcast.com/images/e083_thewraith.jpg", :video => "http://www.youtube.com/watch?v=SVNbvr3nKP8", :imdb => "http://www.imdb.com/title/tt0092240/" },
	{ :number => 82, :location => "http://badmoviepodcast.com/2012/05/episode-82-lunar-cop/", :published => Date.new(2012, 5, 16), :name => "Lunar Cop", :url => "http://badmoviepodcast.com/mp3/e082_lunarcop.mp3", :description => "Post Big-Bird apocalypse, Moonenites have plans to restore Earth to a non-wasteland. They just have to get rid of the annoying people on it. Space is in the title, but motorcycles in the desert is the reality.", :photo => "http://badmoviepodcast.com/images/e082_lunarcop.jpg", :video => "http://www.youtube.com/watch?v=J5EY-_kkhgM", :imdb => "http://www.imdb.com/title/tt0113719/" },
	{ :number => 81, :location => "http://badmoviepodcast.com/2012/05/episode-81-iron-eagle/", :published => Date.new(2012, 5, 10), :name => "Iron Eagle", :url => "http://badmoviepodcast.com/mp3/e081_ironeagle.mp3", :description => "Grand theft F-16. This is 'Not Top Gun', but rather a movie about adult incompetence and teenage empowerment. Also, the power of Freddy Mercury to give you super powers. Use the force, Doug.", :photo => "http://badmoviepodcast.com/images/e081_ironeagle.jpg", :video => "http://www.youtube.com/watch?v=vSR6sxi1RTo", :imdb => "http://www.imdb.com/title/tt0091278/" },
	{ :number => 80, :location => "http://badmoviepodcast.com/2012/05/episode-80-the-killer-eye/",:published => Date.new(2012, 5, 8),:name => "The Killer Eye", :url => "http://badmoviepodcast.com/mp3/e080_killer_eye.mp3", :description => "Creepy Bill and a big sumbitchin' floating eyeball diddle the breasticles of some starlets in this Full Moon turd kicker. With special guest Dirk the Unfortunate.", :photo => "http://badmoviepodcast.com/images/e080_killer_eye.jpg", :video => "http://www.youtube.com/watch?v=mXOvU5kajr0",:imdb => "http://www.imdb.com/title/tt0177886/"},
	{ :number => 79, :location => "http://badmoviepodcast.com/2012/04/episode-79-moon-trap/", :published => Date.new(2012, 4, 26), :name => "MOON TRAP!", :url => "http://badmoviepodcast.com/mp3/e079_moontrap.mp3", :description => "Walter Koenig and Bruce Campbell's Chin travel to the moon to battle some really retarded alien robots. Also, boobs.  Guest reviewers: George Lucas, Batman.", :photo => "http://badmoviepodcast.com/images/e079_moontrap.jpg", :video => "http://www.youtube.com/watch?v=s3AJqPtTRx0", :imdb => "http://www.imdb.com/title/tt0097911/" },
	{ :number => 78, :location => "http://badmoviepodcast.com/2012/04/episode-78-jack-and-jill/", :published => Date.new(2012, 4, 03), :name => "Jack and Jill", :url => "http://badmoviepodcast.com/mp3/e078_JackJill.mp3", :description => "Sandler's cross-dressing comedy 'Jack and Jill' swept all 10 categories at the Razzies 2012. It was the first time in the 32-year history of the Razzies that one movie won all of the awards. However, we loved it. What is wrong with us? (Achievement Unlocked: Razzie Dazzle)", :photo => "http://badmoviepodcast.com/images/e078_JackJill.jpg", :video => "http://www.youtube.com/watch?v=_peFu-411Zw", :imdb => "http://www.imdb.com/title/tt0810913/" },
	{ :number => 77, :location => "http://badmoviepodcast.com/2012/03/episode-77-return-of-the-killer-tomatoes/", :published => Date.new(2012, 3, 27), :name => "Return of the Killer Tomatoes", :url => "http://badmoviepodcast.com/mp3/e077_ReturnKillerTomatoes.mp3", :description => "George Clooney and Karen Mistal battle John Astin's killer tomatoes. Funnier than it has any right to be.  4 easy Stella Starrs.", :photo => "http://badmoviepodcast.com/images/e077_ReturnKillerTomatoes.jpg", :video => "http://www.youtube.com/watch?v=_peFu-411Zw", :imdb => "http://www.imdb.com/title/tt0095989/" },
	{ :number => 76, :location => "http://badmoviepodcast.com/2012/03/episode-76-star-odyssey/", :published => Date.new(2012, 3, 22), :name => "Star Odyssey", :url => "http://badmoviepodcast.com/mp3/e076_StarOdyssey.mp3", :description => "Spaghetti Star Wars. This is pretty much as bad as it can get, I think. Italy made a space movie, and it stinks to the 9th dimension.", :photo => "http://badmoviepodcast.com/images/e076_StarOdyssey.jpg", :video => "http://www.youtube.com/watch?v=_NwikF9LoXY", :imdb => "http://www.imdb.com/title/tt0078317/" },
	{ :number => 75, :location => "http://badmoviepodcast.com/2012/02/episode-75-supspecies/", :published => Date.new(2012, 2, 25), :name => "Subspecies", :url => "http://badmoviepodcast.com/mp3/e075_Subspecies.mp3", :description => "We let Radu drool all over this one. An ancient ugly is loose in Transylvania... and he's... JUICY.", :photo => "http://badmoviepodcast.com/images/e075_Subspecies.jpg", :video => "http://www.youtube.com/watch?v=OP3rbLu4qDY", :imdb => "http://www.imdb.com/title/tt0103002/" },
	{ :number => 74, :location => "http://badmoviepodcast.com/2012/02/episode-74-ghost-rider-vengeanc/", :published => Date.new(2012, 2, 22), :name => "Ghost Rider Vengeance", :url => "http://badmoviepodcast.com/mp3/e074_GhostRider2.mp3", :description => "We recorded this in a bar. Really. Ghost Rider 2 was everything we wanted it to be. We loved it deeply. Don't believe the haters. Nic brought the CAGE RAGE in full force. 5 hellified Stella Stars!", :photo => "http://badmoviepodcast.com/images/e074_GhostRider2.jpg", :video => "http://www.youtube.com/watch?v=purgXaoqhPY", :imdb => "http://www.imdb.com/title/tt1071875/" },
	{ :number => 73, :location => "http://badmoviepodcast.com/2012/02/episode-73-7th-curse-wtf-asia/", :published => Date.new(2012, 2, 19), :name => "7th Curse (WTF Asia?!?)", :url => "http://badmoviepodcast.com/mp3/e073_7thCurse.mp3", :description => "Chow Yun Fat uses a battle fetus and rocket launcher to kill the Crypt Keeper in this WTF Asia masterpiece. It has a BABY JUICER in it. I can't make this shit up.", :photo => "http://badmoviepodcast.com/images/e073_7thCurse.jpg", :video => "http://www.youtube.com/watch?v=JLbdJfiabK8", :imdb => "http://www.imdb.com/title/tt0092273/" },
	{ :number => 72, :location => "http://badmoviepodcast.com/2012/02/episode-72-the-sword-and-the-sorcerer/", :published => Date.new(2012, 2, 01), :name => "The Sword and the Sorcerer", :url => "http://badmoviepodcast.com/mp3/e072_SwordSorceror.mp3", :description => "A Sword with three blades, a girl with two boobs, and a king with one sorcerer. We should have watched cartoons instead.", :photo => "http://badmoviepodcast.com/images/e072_SwordSorceror.jpg", :video => "http://www.youtube.com/watch?v=m7Emt53jHpc", :imdb => "http://www.imdb.com/title/tt0084749/" },
	{ :number => 71, :location => "http://badmoviepodcast.com/2012/01/episode-71-metalstorm-the-boredom-of-jared-zzzzzz/", :published => Date.new(2012, 1, 22), :name => "MetalStorm - The Boredom of Jared-Zzzzzz", :url => "http://badmoviepodcast.com/mp3/e071_Metalstorm.mp3", :description => "Metalstorm - The Boredom of Jared-Zzzzzz... This is the 3D sister film to Episode 8 - Space Hunter.  It's a space western of shitastical proportions.  Just plain bad, but we had fun.", :photo => "http://badmoviepodcast.com/images/e071_Metalstorm.jpg", :video => "http://www.youtube.com/watch?v=Vk1sdBIi53Q", :imdb => "http://www.imdb.com/title/tt0085935/" },
	{ :number => 70, :location => "http://badmoviepodcast.com/2012/01/episode-70-altered-states/", :published => Date.new(2012, 1, 19), :name => "Altered States", :url => "http://badmoviepodcast.com/mp3/e070_AlteredStates.mp3", :description => "Trippy weird psychedelia movie that we sorta like - Altered States. You could say we had a good trip. Nice visuals.", :photo => "http://badmoviepodcast.com/images/e070_AlteredStates.jpg", :video => "http://www.youtube.com/watch?v=MbYT3UclhNY", :imdb => "http://www.imdb.com/title/tt0080360/" },
	{ :number => 69, :location => "http://badmoviepodcast.com/2012/01/episode-69-for-your-height-only/", :published => Date.new(2012, 1, 11), :name => "For Your Height Only", :url => "http://badmoviepodcast.com/mp3/e069_4urheightonly.mp3", :description => "3ft tall phillipino midget James Bond movie. Thank or blame Lugosi, it was his DVD. Also our 2nd year anniversary gala shitfest.", :photo => "http://badmoviepodcast.com/images/e069_4urheightonly.jpg", :video => "http://www.youtube.com/watch?v=F6bW79wMp4w", :imdb => "http://www.imdb.com/title/tt0200642/" },
	{ :number => 68, :location => "http://badmoviepodcast.com/2011/12/episode-68-santas-slay/", :published => Date.new(2011, 12, 24), :name => "Santa's Slay", :url => "http://badmoviepodcast.com/mp3/e068_SantasSlay.mp3", :description => "An all-star cast is wiped out in the first 5 minutes, leaving two kids to run from Evil Santa. Curling saves the world. Don't think too hard, it'll hurt more.", :photo => "http://badmoviepodcast.com/images/e068_SantasSlay.jpg", :video => "http://www.youtube.com/watch?v=FKrsAFWPnl4", :imdb => "http://www.imdb.com/title/tt0393685/" },
	{ :number => 67, :location => "http://badmoviepodcast.com/2011/11/episode-67-the-dark-backward-wtf-bill-paxton/", :published => Date.new(2011, 11, 9), :name => "The Dark Backward (WTF BILL PAXTON?!)", :url => "http://badmoviepodcast.com/mp3/e067_DarkBackward.mp3", :description => "WTF Bill Paxton? No, really... WTF?  The Dark Backward is like falling down stairs in slow motion for an hour, into a pile of shit. Danke Shoen.", :photo => "http://badmoviepodcast.com/images/e067_DarkBackward.jpg", :video => "http://www.youtube.com/watch?v=9L_pcXuJ384", :imdb => "http://www.imdb.com/title/tt0101660/" },
	{ :number => 66, :location => "http://badmoviepodcast.com/2011/10/episode-66-interview-with-big-chuck/", :published => Date.new(2011, 10, 11), :name => "Interview With Big Chuck", :url => "http://badmoviepodcast.com/mp3/e066_BigChuck.mp3", :description => "This is the most important episode of this podcast. Period. I talk to Chuck Schodowski, without whom this show wouldn't exist. Chuck and John Rinaldi are the cohosts of the Big Chuck & Lil John show, on TV8 in Cleveland from 1979-2007.", :photo => "http://badmoviepodcast.com/images/e066_BigChuck.jpg", :video => "http://www.youtube.com/watch?v=9kMNKfRgAVg", :imdb => "http://www.imdb.com/name/nm1727907/" },
	{ :number => 65, :location => "http://badmoviepodcast.com/2011/10/episode-65-deathsport/", :published => Date.new(2011, 10, 07), :name => "DeathSport", :url => "http://badmoviepodcast.com/mp3/e065_deathsport.mp3", :description => "David Carradine and a playmate re-enact Lord of the Rings on motorcycles. Not really. It's worse than that.", :photo => "http://badmoviepodcast.com/images/e065_deathsport.jpg", :video => "http://www.youtube.com/watch?v=ehh2ltAHecM", :imdb => "http://www.imdb.com/title/tt0077414/" },
	{ :number => 64, :location => "http://badmoviepodcast.com/2011/10/episode-64-karate-dog/", :published => Date.new(2011, 10, 05), :name => "Karate Dog", :url => "http://badmoviepodcast.com/mp3/e064_karatedog.mp3", :description => "Karate Dog. Watching this movie with your kids is pretty much child abuse in 43 states. This will not end well.", :photo => "http://badmoviepodcast.com/images/e064_karatedog.jpg", :video => "http://www.youtube.com/watch?v=McGqeq600D8", :imdb => "http://www.imdb.com/title/tt0270882/" },
	{ :number => 63, :location => "http://badmoviepodcast.com/2011/09/episode-63-frankenstein-island/", :published => Date.new(2011, 9, 23), :name => "Frankenstein Island", :url => "http://badmoviepodcast.com/mp3/e063_FrankensteinIsland.mp3", :description => "THE POWER! THE POWER! THE SUCKAGE! The zombies! The pirates! The bikini cave women FROM SPACE!!", :photo => "http://badmoviepodcast.com/images/e063_FrankensteinIsland.jpg", :video => "http://www.youtube.com/watch?v=5u8W5UFUGiM", :imdb => "http://www.imdb.com/title/tt0082410/" },
	{ :number => 62, :location => "http://badmoviepodcast.com/2011/09/episode-62-heartbeeps/", :published => Date.new(2011, 9, 18), :name => "Heartbeeps", :url => "http://badmoviepodcast.com/mp3/e062_Heartbeeps.mp3", :description => "A story of robots in love. Reproduction. Running out of batteries. Be SURE to listen to the 2nd half. We did an after-show where I left the mics on during our usual post-mortem bullshit session.", :photo => "http://badmoviepodcast.com/images/e062_Heartbeeps.jpg", :video => "http://www.youtube.com/watch?v=eJMm7Bcgho4", :imdb => "http://www.imdb.com/title/tt0082507/" },
	{ :number => 61, :location => "http://badmoviepodcast.com/2011/08/episode-61-lifeforce/", :published => Date.new(2011, 8, 30), :name => "LifeForce", :url => "http://badmoviepodcast.com/mp3/e061_lifeforce.mp3", :description => "Warning! Space Vampire shitfest ahead. You have been warned. But hey, on the bright side... BOOBS!", :photo => "http://badmoviepodcast.com/images/e061_lifeforce.jpg", :video => "http://www.youtube.com/watch?v=KqNquDlAanE", :imdb => "http://www.imdb.com/title/tt0089489/" },
	{ :number => 60, :location => "http://badmoviepodcast.com/2011/08/episode-60-discount-cowboys-and-aliens/", :published => Date.new(2011, 8, 14), :name => "Discount Cowboys and Aliens", :url => "http://badmoviepodcast.com/mp3/e060_Oblivion.mp3", :description => "1994's Oblivion. This is Cowboys and Aliens, but with George Takei and Musetta Vander instead of James Bond and Indianna Jones. End result is the same though. Cowboys and Bullshit.", :photo => "http://badmoviepodcast.com/images/e060_Oblivion.jpg", :video => "http://www.youtube.com/watch?v=OukYe0gflSo", :imdb => "http://www.imdb.com/title/tt0110706/" },
	{ :number => 59, :location => "http://badmoviepodcast.com/2011/08/episode-59-two-headed-love-child/", :published => Date.new(2011, 8, 5), :name => "Two Headed Love Child", :url => "http://badmoviepodcast.com/mp3/e059_Gatroid.mp3", :description => "Debbie Gibson, pregnant with my 2-headed love child, fights Tiffany for mall supremacy. Also, A MONKEY is arriving IN ONE HOUR!! Did that make any sense? You just can't explain that.", :photo => "http://badmoviepodcast.com/images/e059_Gatroid.jpg", :video => "http://www.youtube.com/watch?v=R4yBv4sSKTw", :imdb => "http://www.imdb.com/title/tt1680138/" },
	{ :number => 58, :location => "http://badmoviepodcast.com/2011/07/episode-58-omega-doom/", :published => Date.new(2011, 7, 27), :name => "Omega Doom", :url => "http://badmoviepodcast.com/mp3/e058_OmegaDoom.mp3", :description => "We're due for a western... with ROBOTS. But not West World, that's too good for us. Let's try a Fist Full of Dollars remake with zero budget and Rutger Hauer instead. OMEGA DOOM!", :photo => "http://badmoviepodcast.com/images/e058_OmegaDoom.jpg", :video => "http://www.youtube.com/watch?v=aVrw1tFY4QQ", :imdb => "http://www.imdb.com/title/tt0117238/" },
	{ :number => 57, :location => "http://badmoviepodcast.com/2011/07/episode-57-dark-star/", :published => Date.new(2011, 7, 6), :name => "Dark Star", :url => "http://badmoviepodcast.com/mp3/e057_DarkStar.mp3", :description => "John Carpenter's first film. This is where Aliens, The Thing, Halloween, and all that other 80's sci fi came from. We're exploring the roots here, folks. The BAD roots.", :photo => "http://badmoviepodcast.com/images/e057_DarkStar.jpg", :video => "http://www.youtube.com/watch?v=gSccwmmrS5A", :imdb => "http://www.imdb.com/title/tt0069945/" },
	{ :number => 56, :location => "http://badmoviepodcast.com/2011/07/episode-56-transformers-2-jumping-the-sharktacon/", :published => Date.new(2011, 7, 1), :name => "Transformers 2 - Jumping the Sharktacon", :url => "http://badmoviepodcast.com/mp3/e056_Transformers2.mp3", :description => "Transformers 2 is an offensive piece of shit. We roll in it like a stinky dog. Join us in not going to see the 3rd one.", :photo => "http://badmoviepodcast.com/images/e056_Transformers2.jpg", :video => "http://www.youtube.com/watch?v=uH3STHC63hU", :imdb => "http://www.imdb.com/title/tt1055369/" },
	{ :number => 55, :location => "http://badmoviepodcast.com/2011/06/episode-55-black-belt-jones/", :published => Date.new(2011, 6, 26), :name => "Black Belt Jones", :url => "http://badmoviepodcast.com/mp3/e055_blackbeltjones.mp3", :description => "Jim 'The Dragon' Kelly kicks mobster ass to defend his Karate School. He does it in the dark, he does it in a car wash, he does it on the beach. He just does it full time.", :photo => "http://badmoviepodcast.com/images/e055_blackbeltjones.jpg", :video => "http://www.youtube.com/watch?v=66clfRFkEQM", :imdb => "http://www.imdb.com/title/tt0071221/" },
	{ :number => 54, :location => "http://badmoviepodcast.com/2011/05/episode-54-samurai-cop/", :published => Date.new(2011, 5, 25), :name => "Samurai Cop", :url => "http://badmoviepodcast.com/mp3/e054_samuraicop.mp3", :description => "He's not a samurai, despite what they all call him. Probably not a real cop either. This is 4 stars of absurdity though... in Samurai Cop!  They should have called this one 'Martial Law' or 'Copping a Feel'.", :photo => "http://badmoviepodcast.com/images/e054_samuraicop.jpg", :video => "http://www.youtube.com/watch?feature=player_embedded&v=rtj1YJns-WE", :imdb => "http://www.imdb.com/title/tt0130236/" },
	{ :number => 53, :location => "http://badmoviepodcast.com/2011/05/episode-53-future-force-future-zone/", :published => Date.new(2011, 5, 16), :name => "Future Force / Future Zone", :url => "http://badmoviepodcast.com/mp3/e053_FutureForceZone.mp3", :description => "David Carradine and Bad Movie Podcast Alumni Ted Pryor (Mike Danton! Dun-dun-dunnn!) police the future with a time machine and a cybernetic power glove. Yeah, they did that.", :photo => "http://badmoviepodcast.com/images/e053_FutureForceZone.jpg", :video => "http://www.youtube.com/watch?v=yDwlvBS36ws", :imdb => "http://www.imdb.com/title/tt0099624/" },
	{ :number => 52, :location => "http://badmoviepodcast.com/2011/05/episode-52-5-element-ninjas/", :published => Date.new(2011, 5, 8), :name => "5 Element Ninjas", :url => "http://badmoviepodcast.com/mp3/e052_5elementninjas.mp3", :description => "Kung fu vs 5 elemental clans of ninjas. This movie is pretty much a video game. 5 stages, end boss battle. Upgraded weapons along the way. Good fun, and you have to watch it some day.We rated it 3 Stella Stars + 1 indeterminate dangly bit of entrails/scrotum. We're still not sure what that thing was, but it really hurt when he stepped on it.", :photo => "http://badmoviepodcast.com/images/e052_5elementninjas.jpg", :video => "http://www.youtube.com/watch?v=OA68I1u31Z0", :imdb => "http://www.imdb.com/title/tt0084921/" },
	{ :number => 51, :location => "http://badmoviepodcast.com/2011/04/episode-51-robo-geisha-vs-flying-guillotine/", :published => Date.new(2011, 4, 29), :name => "Robo Geisha vs. Flying Guillotine", :url => "http://badmoviepodcast.com/mp3/e051_flyinggeisha.mp3", :description => "Robo Geisha - the first movie we ever walked out of. Flying Guillotine comes to our rescue! Yay!", :photo => "http://badmoviepodcast.com/images/e051_buscemieyes.jpg", :video => "http://www.youtube.com/watch?v=RmdP1qTjGZY", :imdb => "http://www.imdb.com/title/tt0072913/" },
	{ :number => 50, :location => "http://badmoviepodcast.com/2011/07/episode-50-sherman-set-the-wayback-for-dr-who/",:published => Date.new(2011, 7, 13), :name => "Sherman, Set the Wayback for Dr Who", :url => "http://badmoviepodcast.com/mp3/e050_DrWho.mp3", :description => "Dr Who 1996. We go back in time with special guest @tallhatmedia Chris, to try to stop this Eric Roberts atrocity. By the power of William Sasso, the universe is saved. Also, there is not a single Dalek in the whole damn movie. What kind of Dr Who is that?This is a 1 hour and 1 minute LOLgasm. Make sure you're wearing clean underwear, just in case someone has to call an ambulance for you. Also, hope Eric Roberts isn't driving it.", :photo => "", :video => "http://www.youtube.com/watch?v=WA0zenI7_H8", :imdb => "http://www.imdb.com/title/tt0059126/" },
	{ :number => 49, :location => "http://badmoviepodcast.com/2011/04/episode-49-king-kong-escapes/", :published => Date.new(2011, 4, 9), :name => "King Kong Escapes!", :url => "http://badmoviepodcast.com/mp3/e049_kingkongescapes.mp3", :description => "Mechani-kong. When nothing but a giant robot monkey will do, demand the best. Demand Dr. Who's mechanical monkeys. We're sure glad we did, and it shows.", :photo => "http://badmoviepodcast.com/images/e049_kingkongescapes.jpg", :video => "http://www.youtube.com/watch?feature=player_embedded&v=XrUFlFD4Lvo", :imdb => "http://www.imdb.com/title/tt0061868/" },
	{ :number => 48, :location => "http://badmoviepodcast.com/2011/04/episode-48-arena/", :published => Date.new(2011, 4, 3), :name => "Arena", :url => "http://badmoviepodcast.com/mp3/e048_Arena.mp3", :description => "n space, no-one can hear you... zzzzzzzzzzz *urk* gah, uh... Arena! The best space boxing movie ever made! We laughed, we cheered, we tried to stay awake! Horn! Horn am champion! If you want to hear a podcast that LOVED this movie - www.bmfcast.com", :photo => "http://badmoviepodcast.com/images/e048_Arena.jpg", :video => "http://www.youtube.com/watch?v=fHKnU-YkOE4", :imdb => "http://www.imdb.com/title/tt0101366/" },
	{ :number => 47, :location => "http://badmoviepodcast.com/2011/03/episode-47-urban-warriors/", :published => Date.new(2011, 3, 23), :name => "Urban Warriors", :url => "http://badmoviepodcast.com/mp3/e047_UrbanWarriors.mp3", :description => "[EXPLICIT] Solar powered post-apocalyptic mutant cannibal biker gangs. Yes, I said that. It's I Am Legend + Mad Max + Spaghetti Western = Urban Warriors. We really need to learn the lesson, that spaghetti Mad Max movies are always a carpet bombing of pain. We hated on this movie so much it took hour to get it done properly.", :photo => "http://badmoviepodcast.com/images/e047_UrbanWarriors.jpg", :video => "http://www.youtube.com/watch?feature=player_embedded&v=m38DJdfoi2s", :imdb => "http://www.imdb.com/title/tt0289596/" },
	{ :number => 46, :location => "http://badmoviepodcast.com/2011/03/episode-46-green-slime/", :published => Date.new(2011, 3, 20), :name => "Green Slime", :url => "http://badmoviepodcast.com/mp3/e046_GreenSlime.mp3", :description => "Green Slime is clearly the inspiration for Armageddon. The first half of the movie at least. I really wish Bruce Willis had fought rubber tentacle monsters though - would have made a better film of Armageddon for sure", :photo => "http://badmoviepodcast.com/images/e046_GreenSlime.jpg", :video => "http://www.youtube.com/watch?v=g79_ljVC5Wk", :imdb => "http://www.imdb.com/title/tt0064393/" },
	{ :number => 45, :location => "http://badmoviepodcast.com/2011/03/episode-45-drive-funky/", :published => Date.new(2011, 3, 13), :name => "Drive Funky", :url => "http://badmoviepodcast.com/mp3/e045_DriveFunky.mp3", :description => "We sit down with Mike White, author of Impossibly Funky and Cashiers du Cinemart. Then, Jim and Josh discuss the cinematic masterpiece that is Drive Angry 3D. It really was quite good.", :photo => "http://badmoviepodcast.com/images/e045_DriveFunky.jpg", :video => "http://www.youtube.com/watch?v=O2-hiHUh4UQ", :imdb => "http://www.imdb.com/title/tt1502404/" },
	{ :number => 44, :location => "http://badmoviepodcast.com/2011/03/episode-44-r-o-t-o-r/", :published => Date.new(2011, 3, 5), :name => "R.O.T.O.R.", :url => "http://badmoviepodcast.com/mp3/e044_ROTOR.mp3", :description => "Robocop, Terminator, Judge Dredd and a bucket of absurdity. This movie challenges Star Crash for the upper limits of our rating scale. We could hardly get it all into an hour show. This is really top of the bottom of the barrel here. We <3 U Shoeboogie!", :photo => "http://badmoviepodcast.com/images/rotor.jpg", :video => "http://www.youtube.com/watch?v=XJV3qFsaozE", :imdb => "http://www.imdb.com/title/tt0098156/" },
	{ :number => 43, :location => "http://badmoviepodcast.com/2011/02/episode-43-deadly-prey/", :published => Date.new(2011, 2, 27), :name => "Deadly Prey", :url => "http://badmoviepodcast.com/mp3/e043_Deadly_Prey.mp3", :description => "They wanted to hunt a human being. They picked the wrong suburbanite. Take off your shirt, take off your shoes, you're all gonna die. (And a man is beaten to death with his own severed arm... REALLY.)", :photo => "http://badmoviepodcast.com/images/e043_deadly_prey.jpg", :video => "http://www.youtube.com/watch?v=FQySDbFb97s", :imdb => "http://www.imdb.com/title/tt0092848/" },
	{ :number => 42, :location => "http://badmoviepodcast.com/2011/02/episode-42-carnosaur/", :published => Date.new(2011, 2, 20), :name => "Carnosaur", :url => "http://badmoviepodcast.com/mp3/e042_carnosaur.mp3", :description => "Craposaur! Kentucky Fried Raptor! Butt Cluckers! What happens when Dianne Ladd reverse engineers chickens into dinosaurs, and THEN turns them into a virus that gets you pregnant with dinosaur eggs? NOTHING GOOD, that's what! Thanks to Eric @lugosi6 for screwing us by picking this movie as his prize for winning the Arnold contest.", :photo => "http://badmoviepodcast.com/images/e042-carnosaur.jpg", :video => "http://www.youtube.com/watch?v=M0wP4rP6R70", :imdb => "http://www.imdb.com/title/tt0106521/" },
	{ :number => 41, :location => "http://badmoviepodcast.com/2011/02/episode-41-flesh-gordon/", :published => Date.new(2011, 2, 13), :name => "Flesh Gordon", :url => "http://badmoviepodcast.com/mp3/e041_fleshgordon.mp3", :description => "Flesh Gordon, the 1974 burlesque sci-farce about Penisaruses, atomic power pasties, claymation monsters, and a whole lot of wiener and boob jokes. Not particularly good, but our show turned out great. We had our Bulgarian brother Ogi aboard as we set sail for Planet Porno", :photo => "http://badmoviepodcast.com/images/e041_flesh-gordon.jpg", :video => "http://www.youtube.com/watch?v=H0RNauuZ6uQ", :imdb => "http://www.imdb.com/title/tt0080745/" },
	{ :number => 40, :location => "http://badmoviepodcast.com/2011/02/episode-40-jack-frost/", :published => Date.new(2011, 2, 4), :name => "Jack Frost", :url => "http://badmoviepodcast.com/mp3/e040_JackFrost.mp3", :description => "Not THAT movie. This Jack Frost is about a serial killer, some secret military goop, and killing people with the power of terrible puns. Our boy turns into a snowman, conveniently in the snowman capital of the world, and commences to slash and wisecrack. Less than the sum of it's parts, unfortunately.", :photo => "http://badmoviepodcast.com/images/e040.jpg", :video => "http://www.youtube.com/watch?v=VJEm4miHkvI", :imdb => "http://www.imdb.com/title/tt0141109/" },
	{ :number => 39, :location => "http://badmoviepodcast.com/2011/01/episode-39-eliminators/", :published => Date.new(2011, 1, 30), :name => "Eliminators", :url => "http://badmoviepodcast.com/mp3/e039_Eliminators.mp3", :description => "A cyborg, a pirate, a ninja and a scientist walk into a bar in Mexico... that's not a joke, that's the plot of this movie. There are also CAVEMEN and some time travel. We were devastated at the complete lack of dinosaurs. Well, you can't have it all, I guess.", :photo => "http://www.badmoviepodcast.com/images/e039_eliminstors.jpg", :video => "http://www.youtube.com/watch?v=YzfWkQ1R2kY", :imdb => "http://www.imdb.com/title/tt2118617/" },
	{ :number => 38, :location => "http://badmoviepodcast.com/2011/01/episode-38-cannibal-women-in-the-avocado-jungle-of-death/", :published => Date.new(2011, 1, 22), :name => "Cannibal Women in the Avocado Jungle of Death", :url => "http://badmoviepodcast.com/mp3/e038_avacadojungle.mp3", :description => "Cannibal Women are endangering the national avocado reserves. The military sends in Bill Maher and Shannon Tweed to defeat the evil feministas.", :photo => "http://www.badmoviepodcast.com/images/e038.jpg", :video => "http://www.youtube.com/watch?feature=player_embedded&v=htt40ANLwls", :imdb => "http://www.imdb.com/title/tt0094834/" },
	{ :number => 37, :location => "http://badmoviepodcast.com/2011/01/episode-37-gremloids/", :published => Date.new(2011, 1, 15), :name => "Gremloids", :url => "http://badmoviepodcast.com/mp3/e037_gremloids.mp3", :description => "Gremloids: Paula Poundstone, Chris Elliott in a Star Wars spoof that we can only call 'Udderly Ridiculous.' 3 Stella Stars.", :photo => "http://www.badmoviepodcast.com/images/gremloids.jpg", :video => "http://www.youtube.com/watch?feature=player_embedded&v=EuCjU3befRY", :imdb => "http://www.imdb.com/title/tt0087363/" },
	{ :number => 36, :location => "http://badmoviepodcast.com/2010/12/episode-36-boxers-omen/", :published => Date.new(2010, 12, 18), :name => "Boxer's Omen", :url => "http://badmoviepodcast.com/mp3/e036_Boxers_Omen.mp3", :description => "This is the most crazy, black magic, alligator stuffing, chicken testicle chewing, mushroom rubbing, bat impaling, kung fu fighting, apeshit insane movie I have ever seen. CONTEST: Send your best AHNULD impressions to us. Winner will win... something. 919-901-1010. GET TO DA CHOPPAH! DO EEET NOW-AH!", :photo => "", :video => "http://www.youtube.com/watch?v=2LBzqrvicu0", :imdb => "http://www.imdb.com/title/tt0085951/" },
	{ :number => 35, :location => "http://badmoviepodcast.com/2010/12/episode-35-tron-vs-automan/", :published => Date.new(2010, 12, 15), :name => "Tron vs. Automan", :url => "http://badmoviepodcast.com/mp3/e035_tronfest.mp3", :description => "TRON! I love this movie. Automan! I'm embarrassed to have watched this as a kid. We do justice to both on our Tronfest Special Episode!",:photo => "", :video => "http://www.youtube.com/watch?v=3efV2wqEjEY", :imdb => "http://www.imdb.com/title/tt0084827/" },
	{ :number => 34, :location => "http://badmoviepodcast.com/2010/12/episode-34-thankskilling/", :published => Date.new(2010, 12, 5), :name => "ThanksKilling", :url => "http://badmoviepodcast.com/mp3/e034_thankskilling.mp3", :description => "Demonic Zombie Turkey on a $3,500 budget. We scored it 4.5 out of 5. So deeply absurd, it'll be a yearly tradition I think. Gobble Gobble, indeed.", :photo => "", :video => "http://www.youtube.com/watch?feature=player_embedded&v=WOjSRoxc6mg", :imdb => "http://www.imdb.com/title/tt1129441/" },
	{ :number => 33, :location => "http://badmoviepodcast.com/2010/11/episode-33-disorderlies/", :published => Date.new(2010, 11, 13), :name => "Disorderlies", :url => "http://badmoviepodcast.com/mp3/e033_disorderlies.mp3", :description => "The Fat Boys are back! BRRRRRmmm-buha-HA-HA BU BU BU-ha-ha-hur-huh! (that's what they said, anyway.)", :photo => "", :video => "http://www.youtube.com/watch?feature=player_embedded&v=Q1-iC5ZfvLE", :imdb => "http://www.imdb.com/title/tt0092897/" },
	{ :number => 32, :location => "http://badmoviepodcast.com/2010/11/episode-32-leprechaun-4-in-space/", :published => Date.new(2010, 11, 7), :name => "Leprechaun 4 - IN SPACE!", :url => "http://badmoviepodcast.com/mp3/e032-Leprechaun4.mp3", :description => "There's some rule about sequels... putting 'In Space' in the title guarantees that we're all over it. Not that it's really better, but the perceived stink is much higher. Leprechaun really got our expectations up. Didn't really deliver though.", :photo => "", :video => "http://www.youtube.com/watch?feature=player_embedded&v=Q1-iC5ZfvLE", :imdb => "http://www.imdb.com/title/tt0116861/" },
	{ :number => 31, :location => "http://badmoviepodcast.com/2010/10/episode-31-halloween-3/", :published => Date.new(2010, 10, 30), :name => " Halloween 3", :url => "http://badmoviepodcast.com/mp3/e031_H3_SeasonOfTheWitch.mp3", :description => "H3 has nothing to do with the first two movies. That didn't do anyone a favor. Everyone in this movie deserved to die, and I think we died a little watching it. Negative 4 stars. As low as you can go without having Ringo Starr or Nick Cage actually in your movie. We even invoke the name of Cage because this movie is worse than Ghost Rider.", :photo => "", :video => "http://www.youtube.com/watch?v=i6QY5LOa6MM", :imdb => "http://www.imdb.com/title/tt0479997/" },
	{ :number => 30, :location => "http://badmoviepodcast.com/2010/10/episode-30-basket-case/", :published => Date.new(2010, 10 , 17), :name => "Basket Case", :url => "http://badmoviepodcast.com/mp3/e030_basketcase.mp3", :description => "What's in the basket? Sibling rivalry. It's a bromance, where one brother is nuts, and the other is a lump of homicidal grotesque in a wicker basket. Filmed in a service elevator - not kidding. Belial should have quit while he was... a head. (Ba-dump... kshh!)", :photo => "", :video => "http://www.youtube.com/watch?feature=player_embedded&v=ok7fOwdk2gc", :imdb => "http://www.imdb.com/title/tt0083624/" },
	{ :number => 29, :location => "http://badmoviepodcast.com/2010/10/episode-29-son-of-dracula/", :published => Date.new(2010, 10, 17), :name => "Son of Dracula", :url => "http://badmoviepodcast.com/mp3/ep029_SonofDracula.mp3", :description => "Ringo as Merlin, and Nilsson as Count Down. A musical of sorts. Surprsingly not as terrible as I expected. About 40 min in, we talk about REAL sewer monsters... Cameron Village Butt Weasles.", :photo => "", :video => "http://www.youtube.com/watch?v=Qv4y_Y0bKWo", :imdb => "http://www.imdb.com/title/tt0036376/" },
	{ :number => 28, :location => "http://badmoviepodcast.com/2010/10/episode-28-the-equinox/", :published => Date.new(2010, 10, 2), :name => "The Equinox", :url => "http://badmoviepodcast.com/mp3/e028_Equinox.mp3", :description => "EQUINOX! Pack up the Mystery Van and ride along as four college kids explore a gateway to hell... THE EQUINOX! Btw, hell is full of playdoh monsters. Just sayin.", :photo => "", :video => "http://www.youtube.com/watch?feature=player_embedded&v=4gfsvt8YDV8", :imdb => "http://www.imdb.com/title/tt0067055/" },
	{ :number => 27, :location => "http://badmoviepodcast.com/2010/10/episode-27-blacula/", :published => Date.new(2010, 9, 30), :name => "Blacula!", :url => "http://badmoviepodcast.com/mp3/e027_Blacula.mp3", :description => "Blacula! He's Dracula's soul brother, and one bad mutha... hey, wait a minute. He was a pretty cool cat. We'd hang out with him. We have similar taste in movies.", :photo => "", :video => "http://www.youtube.com/watch?feature=player_embedded&v=26jvG4THLIE", :imdb => "http://www.imdb.com/title/tt0068284/" },
	{ :number => 26, :location => "http://badmoviepodcast.com/2010/09/episode-26-conan-the-barbarian/", :published => Date.new(2010, 9, 21), :name => "Conan the Barbarian", :url => "http://badmoviepodcast.com/mp3/e026_Conan.mp3", :description => "CROM!! Bring us a movie worthy of Arnold!  And if you don't... to hell with you!", :photo => "", :video => "http://www.youtube.com/watch?feature=player_embedded&v=OBGOQ7SsJrw", :imdb => "http://www.imdb.com/title/tt0082198/" },
	{ :number => 25, :location => "http://badmoviepodcast.com/2010/09/episode-25-night-of-the-demon/", :published => Date.new(2010, 9, 14), :name => "Night of the Demon", :url => "http://badmoviepodcast.com/mp3/e025_nightofthedemon.mp3", :description => "Bigfoot. RUUUUUaaaaaaaaurrrrrrraaaaarrrruuur. this movie really sucked. 2 Ringos, and that's being kind. PS - Careful if you stop to take a whiz roadside in bigfoot country. Whooo.", :photo => "", :video => "http://www.youtube.com/watch?feature=player_embedded&v=dxM7IG6mdPM", :imdb => "http://www.imdb.com/title/tt0093624/" },
	{ :number => 24, :location => "http://badmoviepodcast.com/2010/09/episode-24-piranha-2-piranha-3d/", :published => Date.new(2010, 9, 2), :name => "Piranha 2 / Piranha 3D", :url => "http://badmoviepodcast.com/mp3/e024_Piranha2.mp3", :description => "'Piranha 2 is the finest movie that has ever been made about flying piranhas.' - James Cameron. Nuff said.", :photo => "", :video => "http://www.youtube.com/watch?feature=player_embedded&v=yN8uUZZWtSk", :imdb => "http://www.imdb.com/title/tt1714203/" },
	{ :number => 23, :location => "http://badmoviepodcast.com/2010/08/episode-23-champions-of-justice/", :published => Date.new(2010, 8, 24), :name => "Champions of Justice", :url => "http://badmoviepodcast.com/mp3/e023_Chamions_of_Justice.mp3", :description => "Blue Demon and his posse of masked wrestlers do battle with Black Hand and his army of super-midgets in this 1971 uh... classic? All I know is, I want that soundtrack.", :photo => "", :video => "http://www.youtube.com/watch?feature=player_embedded&v=PJFo0-WVxr4", :imdb => "http://www.imdb.com/title/tt0261597/" },
	{ :number => 22, :location => "http://badmoviepodcast.com/2010/08/episode-22-warriors-of-the-wasteland/", :published => Date.new(2010, 8, 4), :name => "Warriors of the Wasteland", :url => "http://badmoviepodcast.com/mp3/e022_war_wasteland.mp3", :description => "Spaghetti Road Warrior. That sums it up. Why are people in superhero costumes? Armored golf carts? Hey, what are they gonna do to... OH MY GOD. NOOOOOOOOOOOOOOO. Tell me that didn't happen, please.", :photo => "", :video => "http://www.youtube.com/watch?feature=player_embedded&v=PJFo0-WVxr4", :imdb => "http://www.imdb.com/title/tt0084424/" },
	{ :number => 21, :location => "http://badmoviepodcast.com/2010/07/episode-21-troll-2/", :published => Date.new(2010, 7, 31), :name => "Troll 2", :url => "http://badmoviepodcast.com/mp3/e021_Troll2.mp3", :description => "Hailed as the worst bad movie of all time, it's TROLL 2. Well, we'll be the judge of that claim. We saw it and OH MY GOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOD!", :photo => "", :video => "http://www.youtube.com/watch?feature=player_embedded&v=9KCct4RwLNM", :imdb => "http://www.imdb.com/title/tt0105643/" },
	{ :number => 20, :location => "http://badmoviepodcast.com/2010/07/episode-20-robowar/", :published => Date.new(2010, 7, 23), :name => "Robowar", :url => "http://badmoviepodcast.com/mp3/e020_Robowar.mp3", :description => "Predator? Predator! With Reb Brown! Except not so much Predator, as it is a steaming pile. But hey, we gave it some Stella Stars. I think 2? or was it 3? It left me with brain damage. Eeep-beep-a-dee-bee-boop-greasy!greasy!", :photo => "", :video => "http://www.youtube.com/watch?feature=player_embedded&v=Bq1lq2gEX_o", :imdb => "" },
	{ :number => 19, :location => "http://badmoviepodcast.com/2010/07/episode-19-space-mutiny/", :published => Date.new(2010, 7, 9), :name => "Space Mutiny", :url => "http://badmoviepodcast.com/mp3/e019_space_mutiny.mp3", :description => "MST3K nailed this movie so well. This about covers it. We watched this MST3K episode minutes after recording our podcast above. We laughed so hard the room was spinning.", :photo => "", :video => "http://www.youtube.com/watch?feature=player_embedded&v=4cOwnCnRYJU", :imdb => "http://www.imdb.com/title/tt0096149/" },
	{ :number => 18, :location => "http://badmoviepodcast.com/2010/07/episode-18-american-ninja-2/", :published => Date.new(2010, 7, 3), :name => "American Ninja 2", :url => "http://badmoviepodcast.com/mp3/e018_am_ninja2.mp3", :description => "American Ninja 2 - Two Army ninja-Rangers are sent to a tropical island paradise, and stumble upon an evil drug lord and his army of genetically modified super-ninjas! And that's the part that isn't absurd.", :photo => "", :video => "http://www.youtube.com/watch?v=zJB9vPQ8ydA", :imdb => "http://www.imdb.com/title/tt0092548/" },
	{ :number => 17, :location => "http://badmoviepodcast.com/2010/06/episode-17-hawk-the-slayer/", :published => Date.new(2010, 6, 24), :name => "Hawk the Slayer", :url => "http://badmoviepodcast.com/mp3/e017_HawkTheSlayer.mp3", :description => "Hawk the Slayer: Ripping off the plot and style of a spaghetti western and dropping it in Dungeons & Dragons land. That's a great idea... right?  Right?  Maybe not so much?  1981's Hawk the Slayer has our hero rescuing the nuns from evil Jack Vader Palance, before he ties them to the fantasy equivalent of the railroad tracks - or something like that.", :photo => "", :video => "http://www.youtube.com/watch?feature=player_embedded&v=ORXmKxe-iHk", :imdb => "http://www.imdb.com/title/tt0080846/" },
	{ :number => 16, :location => "http://badmoviepodcast.com/2010/06/episode-16-megaforce/", :published => Date.new(2010, 6, 13), :name => " MEGAFORCE", :url => "http://badmoviepodcast.com/mp3/e016_Megaforce.mp3", :description => "MEGAFORCE! This is what you'd get if you let HotWheels design your army vehicles. The military uniform of the future is a gold spandex jumpsuit - with no pockets.  Barry Bostwick and his blue ascott bring the pain.", :photo => "", :video => "http://www.youtube.com/watch?feature=player_embedded&v=dqCb_9ubQ1U", :imdb => "http://www.imdb.com/title/tt0084316/" },
	{ :number => 15, :location => "http://badmoviepodcast.com/2010/06/episode-15-gymkata/", :published => Date.new(2010, 6, 10), :name => "GYMKATA", :url => "http://badmoviepodcast.com/mp3/e015_Gymkata.mp3", :description => "A martial arts movie where a caucasian olympic gymnast battles Yugoslavians on a pommel horse in the town square of the Village of the Damned. Yep.  That happened.  How bad?  THIS BAD.", :photo => "http://badmoviepodcast.com/images/gymkata_babe.jpg", :video => "http://www.youtube.com/watch?v=9Mkl9rtttog", :imdb => "http://www.imdb.com/title/tt0089243/" },
	{ :number => 14, :location => "http://badmoviepodcast.com/2010/06/episode-14-night-of-the-lepus/", :published => Date.new(2010, 6, 2), :name => "Night of the Lepus", :url => "http://badmoviepodcast.com/mp3/e014_Lepus.mp3", :description => "The HORROR of GIANT RABBITS! Well, ok, there wasn't much horror. The rabbits were mostly confused about what was going on. DeForest Kelley... also confused about why he's in this movie. Think of this as a belated 'Easter Special'.", :photo => "http://badmoviepodcast.com/images/lepus.jpg", :video => "http://www.youtube.com/watch?v=_yww2x3bm9k", :imdb => "http://www.imdb.com/title/tt0069005/" },
	{ :number => 13, :location => "http://badmoviepodcast.com/2010/06/episode-13-buckaroo-banzai-blah-blah-8th-dimension/", :published => Date.new(2010, 6, 2), :name => "Buckaroo Banzai (blah blah 8th Dimension)", :url => "http://badmoviepodcast.com/mp3/e013_Buckaroo_Banzai.mp3",:description => "Peter Weller, Christopher Lloyd, Jeff Goldblum, John Lithgow, Clancy Brown, and more!  An amazing cast for one weird-ass movie.  Buckaroo Banzai and the Hong Kong Cavaliers take on the evil Red Lectroids from the 8th Dimension, with the help of the rastafari Black Lectroids from Planet 10.  If that didn't make sense, none of the rest will either.  Hang onto your socks, we're going for a ride!", :photo => "http://www.badmoviepodcast.com/images/buckaroobanzai.jpg", :video => "http://www.youtube.com/watch?v=0gNJ1z-ulB4", :imdb => "http://www.imdb.com/title/tt0086856/" },
	{ :number => 12, :location => "http://badmoviepodcast.com/2010/05/episode-12-flash-gordon/", :published => Date.new(2012, 6, 1), :name => "Flash Gordon", :url => "http://badmoviepodcast.com/mp3/e012_Flash_Gordon.mp3",  :description => "Flash! AAAAAaaaaaaa! This movie shouldn't be as good as it is. Yet, it's one of the best of the bad! How many times can I abuse Freddy Mercury's sound byte? Find out here in Episode 12!You've seen this movie... right? I can't believe anybody who loves bad movies hasn't seen THIS beast. If not, RUN - don't walk - to get a copy of it. In fact, it just came out on Blu-Ray I heard.This one's dedicated to Klytus, baby.", :photo => "http://www.badmoviepodcast.com/images/vultan.jpg", :video => "http://www.youtube.com/watch?v=uh8KVG8j68I", :imdb => "http://www.imdb.com/title/tt0080745/" },
	{ :number => 11, :location => "http://badmoviepodcast.com/2010/05/episode-11-death-race-2000/", :published => Date.new(2010, 5, 12), :name => "Death Race 2000", :url => "http://badmoviepodcast.com/mp3/e011_DeathRace2000.mp3", :description => "Death Race 2000, the David Carradine camp-fest from 1975.  Carradine, Sylvester Stallone, the bad guy from Karate Kid, and assorted babes race coast-to-coast scoring points for running over pedestrians.  It's sort of Cannonball Run with carnage for score.", :photo => "http://www.badmoviepodcast.com/images/deathrace2000.jpg", :video => "http://www.youtube.com/watch?v=0ZLYEbkykCI", :imdb => "http://www.imdb.com/title/tt0452608/" },
	{ :number => 10, :location => "http://badmoviepodcast.com/2010/05/episode-10-caveman/", :published => Date.new(2010, 5, 12), :name => "Caveman", :url => "http://badmoviepodcast.com/mp3/e010_Caveman.mp3", :description => "Caveman, from 1981 with Ringo Starr, Shelly Long, Barbara Bach, and John Matuszak. I had pretty fond memories of liking this movie as a kid. It was goofy fun. For bad movie night podcast fodder, however, it was pretty uninteresting. Just wasn't so much fun to talk about. We DID manage to create a new review score based on it... the measure of uninteresting movies. The 'Ringo Starr'. This is opposed to the 'Stella Starr' of excellence.", :photo => "http://www.badmoviepodcast.com/images/caveman.gif", :video => "http://www.youtube.com/watch?v=u58TKioxsVs,mg", :imdb => "http://www.imdb.com/title/tt0082146/" },
	{ :number => 9, :location => "http://badmoviepodcast.com/2010/04/episode-9-the-ice-pirates/", :published => Date.new(2010, 4, 26), :name => "The Ice Pirates", :url => "http://badmoviepodcast.com/mp3/e009_Ice_Pirates.mp3", :description => "Space Herpe, we love you. Hard times in space. Water is the only thing of value, and a band of bumbling pirates is out to steal some ice cubes. Instead, they end up with a princess, two donkeys, a goat, a space herpe infestation... and amazon riding unicorns. Pretty much.", :photo => "", :video => "http://www.youtube.com/watch?feature=player_embedded&v=-me2inj1nNw", :imdb => "http://www.imdb.com/title/tt0087451/" },
	{ :number => 8, :location => "http://badmoviepodcast.com/2010/04/episode-8-space-hunter-in-2d/",:published => Date.new(2010, 4, 21), :name => "Space Hunter - in 2D!!", :url => "http://badmoviepodcast.com/mp3/e008_SpaceHunter.mp3", :description => "I don't know how Peter Strauss could stand it.  I also don't know why he carries shampoo around on his Batman Utility Belt.  Some things cannot be explained... IN SPACE!  Michael Ironside is a human crane-game villain. There is a MAZE OF DEATH!!", :photo => "http://badmoviepodcast.com/images/spacehunter.jpg", :video => "http://www.youtube.com/watch?v=z351Gqxiv8E", :imdb => "http://www.imdb.com/title/tt0086346/" },
	{ :number => 7, :location => "http://badmoviepodcast.com/2010/04/up-next-the-thing-with-two-heads/",:published => Date.new(2010, 4, 17), :name => "The Thing With Two Heads", :url => "http://badmoviepodcast.com/mp3/e007_Thing_With_Two_Heads.mp3", :description => "Rosie Grier and Ray Milland star in 'The Thing With Two Heads'. This is the best movie we've seen since Star Crash.  Seriously.", :photo => "", :video => "http://www.youtube.com/watch?feature=player_embedded&v=gWHNA_j7h5A", :imdb => "http://www.imdb.com/title/tt0069372/" },
	{ :number => 6, :location => "http://badmoviepodcast.com/2010/04/episode-6-sean-con-a-thon/",:published => Date.new(2010, 4, 8), :name => "Sean-Con-a-Thon", :url => "http://badmoviepodcast.com/mp3/e006_Sean-Con-a-Thon.mp3", :description => "Sean Connery Con-a-Thon, featuring Highlander 2 & Zardoz! Zardoz speaks... to you!  I'd never seen Highlander 2 before (for good reason) and Josh had never seen the magical Zardoz.  We fixed that.  Oh, did we fix that. Either one of these movies alone would have ended a lesser career.  Sean Connery is a hardy bastard though, and it took League of Extraordinary Gentlemen to get the job done.  We don't dare swim in that turd-bucket though.", :photo => "http://www.badmoviepodcast.com/images/zardoz.jpg", :video => "http://www.youtube.com/watch?v=kbGVIdA3dx0", :imdb => "http://www.imdb.com/title/tt0070948/" },
	{ :number => 5, :location => "http://badmoviepodcast.com/2010/04/episode-5-2010-clash-of-the-titans-special/",:published => Date.new(2010, 4, 3), :name => "2010 Clash of the Titans SPECIAL", :url => "http://badmoviepodcast.com/mp3/e005_Clash_2010.mp3", :description => "Clash of the Titans 2010 Review! This is a spur of the moment thing we didn't really plan on doing. However, this movie sucked so bad, we feel we're doing a public service by venting about it a little", :photo => "http://www.badmoviepodcast.com/images/zeus_liam.jpg", :video => "http://www.youtube.com/watch?v=fj2aDS7FSXo", :imdb => "http://www.imdb.com/title/tt0800320/" },
	{ :number => 4, :location => "http://badmoviepodcast.com/2010/04/episode-4-phantom-phools-day/", :published => Date.new(2010, 3, 29), :name => "Phantom Phools Day", :url => "http://badmoviepodcast.com/mp3/e004_Phantom_Phools_Day.mp3", :description => "The Phantom Menace! We were going to tear this movie up, but once we really started watching it we realized what a masterpiece of storytelling it was. What a great movie this turned out to be!", :photo => "http://www.badmoviepodcast.com/images/gungan-bounty-front.jpg", :video => "http://www.youtube.com/watch?v=I6hOlI9cg4o", :imdb => "http://www.imdb.com/title/tt0120915/" },
	{ :number => 3, :location => "http://badmoviepodcast.com/2010/03/episode-3-robot-jox/", :published => Date.new(2010, 3, 25), :name => "Robot Jox", :url => "http://badmoviepodcast.com/mp3/e003_Robot_Jox.mp3", :description => "Stop-motion animated giant robots battle for the future!  It is post-World War III. War is outlawed. Bad movies are still legal though.  This episode is a double feature! We covered Robot Jox 1 & 2.", :photo => "http://badmoviepodcast.com/images/robot_jox.jpg", :video => "http://www.youtube.com/watch?v=8Kd642Ix5ks", :imdb => "http://www.imdb.com/title/tt0102800/" },
	{ :number => 2, :location => "http://badmoviepodcast.com/2010/03/episode-2-war-in-outer-space/", :published => Date.new(2010, 3, 10), :name => "The War in Space", :url => "http://badmoviepodcast.com/mp3/e002_War_In_Space.mp3", :description => "In space... no one can hear you stink.Boy they were in a hurry at Toho to get out something to cash in on that Star Wars mania.  They tried, and failed.", :photo => "http://www.badmoviepodcast.com/images/war-in-space-dvd-cover.jpg", :video => "http://www.youtube.com/watch?v=HzTh_Z-AsDE", :imdb => "" },
	{ :number => 1, :location => "http://badmoviepodcast.com/2010/02/episode-6-humanoids-from-the-deep-2/", :published => Date.new(2010, 3, 10), :name => "Humanoids from the Deep", :url => "http://badmoviepodcast.com/mp3/e001_Humanoids_From_The_Deep.mp3", :description => "Dr. Drake has come to conduct a scientific study of the local fish life and notices an unusual amount of chemicals have createdmutated fish-like creatures that actually are in the process of mating with the female population of humans in the town. When the humanoids from the deep attack the townsfolk at the annual salmon fest many of the conflicts that divide the people are overcome in the effort to band together to fight the monsters.",:photo => "http://www.badmoviepodcast.com/images/humanoidsdeep.jpg",:video => "http://www.youtube.com/watch?v=tzIOSKfS_j4",:imdb => "http://www.imdb.com/title/tt0080904/" }
]

set :public_folder, File.dirname(__FILE__) + '/static'

before do
  cache_control :public, :must_revalidate, :max_age => 60
end

get '/' do
	redirect "/episodes"
end

get '/episodes' do
	last_modified Date.new(2012, 8, 16)
	content_type :json
	episodes.to_json
end

get '/episodes/:episode' do
	last_modified episodes.first[:published]
	content_type :json
	episodes.select { |e| e[:number] == params[:episode].to_i }.to_json
end